dictionaries = ["en_us"]
words = [
    "BDD",
    "Bulbapedia",
    "Chesto",
    "DEBUFF",
    "Effectivenesss",
    "Flawfinder",
    "Invocable",
    "NODISCARD",
    "NOINLINE",
    "NVE",
    "Spdlog",
    "Valgrind",
    "Winline",
    "Wsuggest",
    "accessors",
    "bugprone",
    "ccache",
    "cconcepts",
    "clangd",
    "cmake",
    "codeql",
    "constexpr",
    "cout",
    "cppcheck",
    "cppcoreguidelines",
    "cx",
    "freflection",
    "frelection",
    "gcda",
    "gcov",
    "genhtml",
    "getters",
    "googletest",
    "gprof",
    "gtest",
    "identifier's",
    "lcov",
    "libconfigcat",
    "libcurl",
    "libhash",
    "libspdlog",
    "libstd",
    "libstdc",
    "lookups",
    "matchers",
    "matchups",
    "noexcept",
    "nonnull",
    "nproc",
    "pocketcore",
    "pointee",
    "pthread",
    "rvalue",
    "semgrep",
    "sfloat",
    "shellcheck",
    "shellfmt",
    "suppressions",
    "vcpkg",
]
