dictionaries = ["en_us"]
words = [
    "Bulbapedia",
    "Chesto",
    "NODISCARD",
    "NOINLINE",
    "NVE",
    "Spdlog",
    "Winline",
    "ccache",
    "cconcepts",
    "clangd",
    "cmake",
    "codeql",
    "cout",
    "cx",
    "genhtml",
    "getters",
    "googletest",
    "lcov",
    "libstd",
    "libstdc",
    "matchups",
    "pocketcore",
    "semgrep",
    "sfloat",
    "shellcheck",
    "shellfmt",
]
