/*! @file constants.h
	@brief Contains constexpr assert message strings for the nature registry.
	@date 09/11/2026
	@since 0.11.6
	@version 0.12.23
	@author Matthew Moore
*/

#ifndef INCLUDE_NATURE_CONSTANTS_H
#define INCLUDE_NATURE_CONSTANTS_H

#include <array>
#include <string_view>

#include "Configuration/constants.h"
#include "Core/typedefs.h"
#include "Pokemon/pokemonMeta.h"

namespace PocketCore::Nature
{
	using PocketCore::Configuration::NATURE_STAT_BASE_MULTIPLIER;
	using PocketCore::Configuration::NATURE_STAT_BOOST_MULTIPLIER;
	using PocketCore::Configuration::NATURE_STAT_WEAKNESS_MULTIPLIER;
	using PocketCore::Core::ub;
	using PocketCore::Pokemon::POKEMON_STAT_COUNT;

	constexpr std::string_view NATURE_NAME_NONE{"None"};
	constexpr std::string_view NATURE_NAME_HARDY{"Hardy"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> HARDY_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_LONELY{"Lonely"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> LONELY_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_BRAVE{"Brave"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> BRAVE_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_WEAKNESS_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_ADAMANT{"Adamant"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> ADAMANT_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,	 NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_NAUGHTY{"Naughty"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> NAUGHTY_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,	  NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_BOLD{"Bold"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> BOLD_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,	  NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_DOCILE{"Docile"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> DOCILE_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_RELAXED{"Relaxed"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> RELAXED_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_IMPISH{"Impish"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> IMPISH_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,	 NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,
		NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_LAX{"Lax"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> LAX_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,	  NATURE_STAT_BOOST_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_TIMID{"Timid"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> TIMID_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,	  NATURE_STAT_BOOST_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_HASTY{"Hasty"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> HASTY_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_SERIOUS{"Serious"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> SERIOUS_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_JOLLY{"Jolly"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> JOLLY_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,	 NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_NAIVE{"Naive"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> NAIVE_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,	  NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_MODEST{"Modest"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> MODEST_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,	   NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_MILD{"Mild"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> MILD_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER,
		NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_QUIET{"Quiet"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> QUIET_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_BASHFUL{"Bashful"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> BASHFUL_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_RASH{"Rash"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> RASH_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_BASE_MULTIPLIER,	   NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_CALM{"Calm"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> CALM_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER,	  NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_GENTLE{"Gentle"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> GENTLE_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_WEAKNESS_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_SASSY{"Sassy"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> SASSY_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_WEAKNESS_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_CAREFUL{"Careful"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> CAREFUL_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER,	 NATURE_STAT_BASE_MULTIPLIER,  NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_WEAKNESS_MULTIPLIER, NATURE_STAT_BOOST_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

	constexpr std::string_view NATURE_NAME_QUIRKY{"Quirky"};
	inline constexpr std::array<double, POKEMON_STAT_COUNT> QUIRKY_STAT_MULTIPLIERS{
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
		NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER, NATURE_STAT_BASE_MULTIPLIER,
	};

} // namespace PocketCore::Nature

#endif
